### ISSUE TITLE
Errors on Dartium console when it enables screen resolution emulation.

### ISSUE THREAD

**Issue by ntaoo** [dart-lang/polymer-dart#58]
On Dartium, when using screen resolution, I confirmed error console messages below at polymer-spa-example and my own app with latest polymer(0.16.1+2) and paper/core- element(0.7.0).

Here is the console message.

interop_support.js:72 Already have a Dart type associated with core-a11y-keys
interop_support.js:72 Already have a Dart type associated with core-selection
interop_support.js:72 Already have a Dart type associated with core-selector
interop_support.js:72 Already have a Dart type associated with core-animated-pages
interop_support.js:72 Already have a Dart type associated with core-meta
interop_support.js:72 Already have a Dart type associated with core-iconset
interop_support.js:72 Already have a Dart type associated with core-icon
interop_support.js:72 Already have a Dart type associated with core-iconset-svg
interop_support.js:72 Already have a Dart type associated with core-icon-button
interop_support.js:72 Already have a Dart type associated with core-menu
interop_support.js:72 Already have a Dart type associated with core-toolbar
interop_support.js:72 Already have a Dart type associated with core-media-query
interop_support.js:72 Already have a Dart type associated with core-drawer-panel
interop_support.js:72 Already have a Dart type associated with core-header-panel
interop_support.js:72 Already have a Dart type associated with core-scaffold
interop_support.js:72 Already have a Dart type associated with paper-ripple
interop_support.js:72 Already have a Dart type associated with paper-button-base
interop_support.js:72 Already have a Dart type associated with paper-item
undefined:1 Exception: Uncaught Error: Already registered (Polymer) prototype for element core-xhr-dart
Stack Trace:
#0      JsFunction.apply (dart:js:254)
#1      Polymer.register (package:polymer/src/instance.dart:169:48)
#2      CustomTag.initialize (package:polymer/src/initializers.dart:12:41)
#3      loadInitializers.<anonymous closure>.<anonymous closure> (package:initialize/src/static_loader.dart:46:42)
#4      _runInitQueue (package:initialize/initialize.dart:35:24)
#5      run (package:initialize/initialize.dart:27:23)
#6      run (package:web_components/src/static_initializer.dart:15:13)
#7      initWebComponents.<anonymous closure> (package:web_components/src/init.dart:28:38)
#8      _RootZone.runUnary (dart:async/zone.dart:1155)
#9      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#10     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#11     _Future._completeWithValue (dart:async/future_impl.dart:358)
#12     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#13     _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#14     _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#15     _handleMutation (dart:html:42316)

**Comment by jakemac53** [comment]
This is probably happening because of an html import to the wrong `packages` folder. The rules for this are somewhat complicated, I would reference this doc https://www.dartlang.org/polymer-old/app-directories.html#importing-assets.

**Comment by zoechi** [comment]
Interesting that in this project (link in the comments) only produces this errors in device mode http://stackoverflow.com/questions/33242044/error-on-changing-to-device-mode-already-have-a-dart-type-associated

**Comment by cbobach** [comment]
I have had the same problem and striped it down to a single page app and hosted on [github]https://github.com/cbobach/spa_error). Hope it can cast some light over the problem.
