### ISSUE TITLE
Strange bug when updating element on a list (polymer 1.0.0-rc.1)

### ISSUE THREAD

**Issue by dam0vm3nt** [dart-lang/polymer-dart#591]
test_element.html:
```html
<dom-module id="test-element">
    <style>

    </style>
    <template>
        <template is="dom-repeat" items="{{samples}}">
            <div>
                <ul>
                    <li><span>{{index}}</span> OBJ:"<span>{{item}}</span>" f1:"<span>{{item.field1}}</span>" -
                        f2:"<span>{{item.field2}}</span>" - f1(func):"<span>{{field1(item)}}</span>"
                    </li>
                </ul>
            </div>
        </template>

    </template>
</dom-module>

<dom-module id="test-main">
    <style >
        div.new {
            padding:1em;
            margin:0.5em;
            background-color: black;
            color:white;
            display: inline-block;
        }

        .old {
            background-color: grey;
            padding:1em;
            margin:0.5em;
            color:black;
            display: inline-block;
        }
    </style>
    <template>
        <div>
            <h1>First</h1>
            <br>
            <test-element samples="[[samples]]"></test-element>
        </div>
        <div>
            <h1>Second</h1>
            <br>
            <test-element samples="[[samples]]"></test-element>
        </div>
        <div>
            <div class="new" on-click="addInitial">Add initial</div>

            <div class="new" on-click="clickMe">Add at 1</div>
            <div class="new" on-click="removeMe">Remove First</div>
            <div class="new" on-click="updateMe">Update at 1</div>
            <div class="new" on-click="testSome">TEST SOME</div>
            <div class="new" on-click="addEnd">Add end</div>
            <div class="new" on-click="removeEnd">Remove end</div>
        </div>
        <div>
            <div class="old" on-click="addEnd2">Add end (using API)</div>
            <div class="old" on-click="addMe2">Add at 1 (using api)</div>
            <div class="old" on-click="removeMe2">Remove First (using API)</div>
            <div class="old" on-click="updateMe2">Update at 1 (using API)</div>
            <div class="old" on-click="doMany">Do step <span>{{step}}</span></div>

        </div>
    </template>
</dom-module>
```

test_element.dart:
```dart
@HtmlImport("test_element.html")
library test.element;

import 'package:polymer/polymer.dart';
import "package:web_components/web_components.dart" show HtmlImport;
import "package:observe/observe.dart";
import "package:polymer_autonotify/polymer_autonotify.dart";

import "dart:html";
import "package:logging/logging.dart";
import "dart:js";

class Sample extends Observable with JsProxy {

  @observable String field1;
  @observable String field2;

  Sample(this.field1,this.field2);

  String toString() => "S(${field1};${field2})";
}

@PolymerRegister("test-element")
class TestElement extends PolymerElement with Observable/* , PolymerAutoNotifySupportMixin*/ {
  static final Logger _logger = new Logger("test.element.TestElement");

  @observable @property List<Sample> samples;

  @eventHandler
  String field1(Sample s) =>s.field1;

  TestElement.created() : super.created() {
  //  PolymerAutoNotifySupportMixin.created(this);
  }

  factory TestElement() => (new Element.tag("test-element") as TestElement);

}

int counter = 0;

@PolymerRegister("test-main")
class TestMain extends PolymerElement with Observable/*, PolymerAutoNotifySupportMixin */{
  static final Logger _logger = new Logger("test.element.TestMain");

  @observable @property List<Sample> samples = new ObservableList();


  @property int step=1;

  @eventHandler
  String clickMe([_,__]) {
    print("CLICKED");
    samples.insert(1,new Sample("ciao${counter++}","ciao${counter++}"));
  }

  @eventHandler
  void removeMe([_,__]) {
    if (samples.isNotEmpty) {
      samples.removeAt(0);
    }
  }

  @eventHandler
  void removeMe2([_,__]) {
    removeAt("samples",0);
  }

  @eventHandler
  void addInitial([_,__]) {
    samples.addAll([
      new Sample("1,1","1,2"),
      new Sample("2,1","2,2")
    ]);
  }

  @eventHandler
  void updateMe([_,__]) {
    samples[1].field1="CHANGED";
    print("CHANGED");
  }

  @eventHandler
  void updateMe2([_,__]) {
    set("samples.1.field1","CHANGED");
  }

  @eventHandler
  void addEnd([_,__]) {
    samples.add(new Sample("ciao${counter++}","ciao${counter++}"));
  }

  @eventHandler
  void addEnd2([_,__]) {
    add("samples",new Sample("ciao${counter++}","ciao${counter++}"));
  }

  @eventHandler
  void removeEnd([_,__]) {
    samples.removeLast();
  }

  @Observe("samples.splices")
  void samplesChanged(splices) {
    print("SAMPLES CHANGED :${splices}");
  }

  @eventHandler
  void testSome([_,__]) {
    var list = new ObservableList.from(["a","b","c"])
      ..listChanges.listen((List<ListChangeRecord> changes) {
        changes.forEach((ListChangeRecord rec) {
          print("CHANGED :${rec}");
        });
    });
    JsArray js =new JsArray.from(list);
    js.callMethod("splice",[1,0,"d"]);
    print("JS FINAL : ${js}");
    print("LIST FINALE :${list}");
  }

  @eventHandler
  void addMe2([_,__]) {
    insert("samples",1,new Sample("banana-${counter++}","papaghena-${counter++}"));
  }

  @eventHandler
  void doMany([_,__]) {
    [
      () => addEnd2(),
          () => addEnd2(),
          () => addEnd2(),
          () => updateMe2(),
          () => removeMe2(),
          () => updateMe2()
    ][step-1]();

    set("step",step+1);

  }

  TestMain.created() : super.created() {
   // PolymerAutoNotifySupportMixin.created(this);
  }

  factory TestMain() => (new Element.tag("test-main") as TestMain);

}

```
Doing the following operations to an array gives an exception : 
 1. add an element 
 2. add an element
 3. add an element
 4. update the element with index 1
 5. remove the first element
 6. update the element with index 1.

This can be achieved by Clicking 6 times on the button "Step x" on the example above.
The reported exception is:
```
Uncaught Unhandled exception:
TypeError: Cannot read property '__dartClass__' of undefined
#0      JsObject._callMethod (dart:js:678)
#1      JsObject.callMethod (dart:js:618)
#2      HtmlElement&PolymerMixin&PolymerBase.set (package:polymer_interop/src/polymer_base.dart:315:17)
#3      TestMain.updateMe2 (http://localhost:63342/Project%20Elys/elys/web/test_element.dart:85:5)
#4      TestMain.doMany.<anonymous closure> (http://localhost:63342/Project%20Elys/elys/web/test_element.dart:135:17)
#5      TestMain.doMany (http://localhost:63342/Project%20Elys/elys/web/test_element.dart:136:14)
#6      Function._apply (dart:core-patch/function_patch.dart:7)
#7      Function.apply (dart:core-patch/function_patch.dart:28)
#8      _InstanceMirrorImpl.invoke (package:reflectable/src/reflectable_transformer_based.dart:161:23)
#9      _setupEventHandlerMethods.<anonymous closure>.<anonymous closure> (package:polymer/src/common/polymer_descriptor.dart:151:31)
  (anonymous function)	
  (anonymous function)	
  handler	
```

**Comment by dam0vm3nt** [comment]
Verified the bug is not present on latest "behaviors" branch.

**Comment by dam0vm3nt** [comment]
bug is not present in 1.0-rc1
