### ISSUE TITLE
1.0.0-rc2 always throws `method not found: 'observe' Receiver: null` after page load

### ISSUE THREAD

**Issue by zoechi** [dart-lang/polymer-dart#614]
>Observatory listening at http://127.0.0.1:60914/
constructor != null && jsTypeName.length > 0
 #0      debug_or_assert (dart:html:1256)
#1      wrap_jso (dart:html:1182)
#2      MutationObserver._create (dart:html:27264)
#3      MutationObserver.MutationObserver._ (dart:html:27227)
#4      MutationObserver.MutationObserver (dart:html:27326)
#5      _ScheduleImmediateHelper._ScheduleImmediateHelper.<anonymous closure> (dart:html:48747)
#6      _RootZone.run (dart:async/zone.dart:1160)
#7      _ScheduleImmediateHelper._ScheduleImmediateHelper (dart:html:48744)
#8      _scheduleImmediateHelper (dart:html:48770)
#9      _scheduleImmediateHelper (dart:html:48769)
#10     _scheduleImmediateClosure.<anonymous closure> (dart:html:48773)
#11     _AsyncRun._scheduleImmediate (dart:async-patch/schedule_microtask_patch.dart:10)
#12     _scheduleAsyncCallback (dart:async/schedule_microtask.dart:73)
#13     _rootScheduleMicrotask (dart:async/zone.dart:957)
#14     scheduleMicrotask (dart:async/schedule_microtask.dart:138)
#15     Future.Future.microtask (dart:async/future.dart:142)
#16     main (http://localhost:63342/polymer1/auto_binding_element/web/index_reflectable_original_main.dart)
#17     main (http://localhost:63342/polymer1/auto_binding_element/web/index.dart:26:10)
#18     main (http://localhost:63342/polymer1/auto_binding_element/web/index.bootstrap.dart:5:11)
#19     main (http://localhost:63342/polymer1/auto_binding_element/web/index.bootstrap.initialize.dart:30:10)

> index_reflectable_original_main.dart:1 Exception: The null object does not have a method 'observe'.
>
NoSuchMethodError: method not found: 'observe'
Receiver: null
Arguments: [Instance of 'DivElement', attributes: true]
main index_reflectable_original_main.dart:1 
main index.dart:29 
main index.bootstrap.dart:5 
main index.bootstrap.initialize.dart:36 main

**Comment by zoechi** [comment]
Seems again to be a problem with bleeding edge Dartium :-/
