### ISSUE TITLE
@Property on `List get foo` blows up

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/polymer-dart#622]
Seems there is a missing reflection capability

```
  // works
  @Property()
  List<String> foos = ['foo1'];

  // doesn't work
  @Property()
  List<String> get foos => ['foo1'];

```

```
Exception: Uncaught Error: Reflecting on class 'ClassMirror on 'List'' without capability
Stack Trace:
#0      wrapClassMirrorIfSupported (package:reflectable/src/reflectable_mirror_based.dart:35:7)
#1      wrapTypeMirror (package:reflectable/src/reflectable_mirror_based.dart:95:12)
#2      MethodMirrorImpl.returnType (package:reflectable/src/reflectable_mirror_based.dart:881:12)
#3      _getPropertyInfoForType (package:polymer/src/common/polymer_descriptor.dart:180:41)
#4      _buildPropertiesObject.<anonymous closure> (package:polymer/src/common/polymer_descriptor.dart:56:24)
#5      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#6      _buildPropertiesObject (package:polymer/src/common/polymer_descriptor.dart:54:16)
#7      createPolymerDescriptor (package:polymer/src/common/polymer_descriptor.dart:25:19)
#8      PolymerRegister.initialize (package:polymer/src/common/polymer_register.dart:19:36)
```

**Comment by zoechi** [comment]
Worked for me https://github.com/bwu-dart-contributing/polymer_elements/blob/demo2/demo/web/all_demos.dart#L132
What version of reflectable are you using?

**Comment by Andersmholmgren** [comment]
0.3.2 (the latest). I started by generating the app from `stagehand web-polymer` with the latest stagehand

**Comment by zoechi** [comment]
I haven't tried 0.3.2 yet, only 0.3.1

**Comment by Andersmholmgren** [comment]
I got the same with 0.3.1

I cloned your demo and thought I saw it was using 0.2.1

**Comment by zoechi** [comment]
I'm still working on upgrading to the newest Polymer version and haven't checked in the latest changes yet.

**Comment by dam0vm3nt** [comment]
I'm using the latest of everything and `List` properties are definitively
working for me.

Il giorno dom 11 ott 2015 10:21 Günter Zöchbauer <notifications@github.com>
ha scritto:

**Comment by jakemac53** [comment]
closing for now as I assume this is stale, please reopen if that is not the case
