### ISSUE TITLE
Starting Observatory failed to find resources

### ISSUE THREAD

**Issue by TylerThompson** [dart-lang/polymer-dart#670]
Refused to execute script from 'http://127.0.0.1:61267/packages/web_components/webcomponents.min.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:61267/packages/web_components/dart_support.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
127.0.0.1/:1 Refused to execute script from 'http://127.0.0.1:61267/packages/polymer_interop/src/js/polymer.min.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
:61267/index.html.polymer.bootstrap.dart.js:19192 INFO: 2015-12-30 11:32:07.257: Starting Observatory
:61267/index.html.polymer.bootstrap.dart.js:30381 Unable to find Polymer. Please make sure you are waiting on initWebComponents() or initPolymer() before attempting to use Polymer.
:61267/index.html.polymer.bootstrap.dart.js:1056 Uncaught Uncaught Error: Bad state: An error occurred initializing polymer, (could notfind polymer js). Please file a bug at https://github.com/dart-lang/polymer-dart/issues/new.
Stack Trace:
Bad state: An error occurred initializing polymer, (could notfind polymer js). Please file a bug at https://github.com/dart-lang/polymer-dart/issues/new.
    at dart.k (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:1610:3)
    at dart.Z7 (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:28325:20)
    at abb.dart.abb.$1 (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:28986:3)
    at Xq.dart.Xq.f5 (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:13432:41)
    at Wo.dart.Wo.$0 (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:12388:21)
    at dart.I.static.ee (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:12342:40)
    at I.dart.I.nA (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:12298:3)
    at Wj.dart.Wj.$0 (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:12381:23)
    at xF.dart.xF.dm (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:12463:30)
    at J.zL (http://127.0.0.1:61267/index.html.polymer.bootstrap.dart.js:36143:32)

**Comment by zoechi** [comment]
What Dart version?

**Comment by jakemac53** [comment]
Please provide minimal repro instructions and reopen

**Comment by TylerThompson** [comment]
I apologize for the very late reply, I believe it was version 1.13 but I have not experienced this since I filed the issue
